# Generated by Django 3.1.1 on 2020-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='',
                                   max_length=120),
        ),
    ]
