# Generated by Django 3.1 on 2020-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='urlToImage',
            field=models.CharField(max_length=255),
        ),
    ]
