# Generated by Django 3.1.1 on 2020-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDescription',
            field=models.TextField(max_length=1200),
        ),
    ]
